### ISSUE TITLE
Hightlight GA

### ISSUE THREAD

**Issue by m1ga** [dbankier/tisdk#1]
Awesome script! Thank you. A small suggestion:

output is

```
4.1.0.Beta
4.0.0.RC5
4.0.0.RC4
4.0.0.RC3
4.0.0.RC2
4.0.0.RC
4.0.0.GA
4.0.0.Beta4
4.0.0.Beta3
4.0.0.Beta2
3.5.1.RC
3.5.1.GA
3.5.1.Alpha
3.5.0.RC3
3.5.0.RC2
3.5.0.RC
3.5.0.GA
```

at the moment. It would be easier to spot GA if they are separated form the rest or just bold

4.1.0.Beta
4.0.0.RC5
4.0.0.RC4
4.0.0.RC3
4.0.0.RC2
4.0.0.RC
**4.0.0.GA**
4.0.0.Beta4
4.0.0.Beta3
4.0.0.Beta2
3.5.1.RC
**3.5.1.GA**
3.5.1.Alpha
3.5.0.RC3
3.5.0.RC2
3.5.0.RC
**3.5.0.GA**

**Comment by dbankier** [comment]
done
