### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by kopiro** [dbankier/tisdk#12]
Tisdk doesn't seems to work anymore.

https://api.github.com/repos/appcelerator/titanium_mobile/tags?per_page=50
http://builds.appcelerator.com/mobile/5_0_X/index.json

It's not be able to find the corresponding sha1 tag, so it doesn't find the right build.

---

Maybe you can download directly from 
http://builds.appcelerator.com/mobile-releases/5.0.2/mobilesdk-5.0.2.GA-osx.zip

**Comment by dbankier** [comment]
Hi. I didn't know about that direct download link...
Since they stopped sharing the GA builds (aside from that link - where did you find it?), you can use the `tisdk build` command to build it yourself.

**Comment by kopiro** [comment]
I find it installing with `appc ti sdk install`.
May be a PR to download SDK from that link would be appreciated?

**Comment by dbankier** [comment]
given that appc is a subscription access cli, I'm not sure if we can rely on that link being open...
