### ISSUE TITLE
Appcelerator replaced scons and python with node scripts

### ISSUE THREAD

**Issue by rbrki07** [dbankier/tisdk#14]
Hi David,

I just tried to build SDK 6.0.0.GA and got the following error message:

`scons: *** No SConstruct file found`

After a few minutes of searching I found https://jira.appcelerator.org/browse/TIMOB-23576. They say 

> We have replaced scons on master branch. There will be a blog post soon.

On June the 24th Appcelerator added a new section "Building Locally" to the README.md file of their Git repository "titanium_mobile" (see: https://github.com/appcelerator/titanium_mobile/blob/881c045d606d1da22a2264e60ce6c6c902181c50/README.md).

Do you have any plans to modify tisdk to support the new build mechanism?

Kind regards,

René

**Comment by dbankier** [comment]
Yep. I will update unless you beat me to it.
