### ISSUE TITLE
what's going on with 5.0.0.GA

### ISSUE THREAD

**Issue by Sophrinix** [dbankier/tisdk#8]
```
✗ tisdk list
5.0.0.RC
5.0.0.GA
5.0.0.Beta
4.1.1.GA
4.1.0.GA
4.1.0.Beta
4.0.0.RC5
4.0.0.RC4
4.0.0.RC3
4.0.0.RC2
4.0.0.RC
4.0.0.GA
4.0.0.Beta4
4.0.0.Beta3
4.0.0.Beta2
3.5.1.RC
3.5.1.GA
3.5.1.Alpha
3.5.0.RC3
3.5.0.RC2
3.5.0.RC
3.5.0.GA
3.5.0.Beta
3.5.0.Alpha
3.4.1.RC
3.4.1.GA
3.4.0.RC2
3.4.0.RC
3.4.0.GA
3.3.0.RC2
3.3.0.RC
3.3.0.GA
3.3.0.Beta
3.3.0.Alpha3
3.3.0.Alpha2
3.3.0.Alpha
3.2.3.RC
✗ tisdk install 5.0.0.GA
Build not available.
```

Any ideas?

**Comment by dbankier** [comment]
Yep. They aren't releasing it as part of nighties any more.

BUT, I just released a new version that automatically checks out the correct commit, builds and installs it. It takes a little bit longer, but you get the same result.

Install the latest - on npm. Setup your environment (see the README). Then `tisdk build 5.0.0.GA`. I'm using it that way now.
